### ISSUE TITLE
Pymel and maya 2025

### ISSUE THREAD

**Issue by CraigLaMorte** [LumaPictures/pymel#474] opened 2024-04-09 21:26 UTC
looks like pymel isn't working with maya 2025

**Comment by iamsleepy** [comment] 2024-05-03 08:12
I've created a fork and generated 2025 docs for it. It seems working fine on my Windows machine.

**Comment by CraigLaMorte** [comment] 2024-05-09 15:58
How do i install the package from your fork?

**Comment by DouglasWilcox** [comment] 2024-05-09 17:24
> How do i install the package from your fork?

@CraigLaMorte I was able to get this working in Maya2025 by downloading the zip, then adding the pymel and docs folders to sys.path.  Not sure if docs needs to be on path.

**Comment by CraigLaMorte** [comment] 2024-05-09 20:05
worked, thanks!

**Comment by iamsleepy** [comment] 2024-05-10 00:57
I have provided a wheel in the release page.

https://github.com/iamsleepy/pymel/releases/tag/1.4.1b1

and it could be installed with pip like below:

`mayapy -m install pymel-1.4.1b1-py2.py3-none-any.whl --user`

**Comment by bohdon** [comment] 2024-05-18 21:37
Thanks for working on this @iamsleepy, really hope pymel doesn't die 😞. I think you're missing `pip` in the command? e.g.
```
mayapy -m pip install pymel-1.4.1b1-py2.py3-none-any.whl --user
```

**Comment by iamsleepy** [comment] 2024-05-19 00:58
> Thanks for working on this @iamsleepy, really hope pymel doesn't die 😞. I think you're missing `pip` in the command? e.g.
> 
> ```
> mayapy -m pip install pymel-1.4.1b1-py2.py3-none-any.whl --user
> ```

Thanks for pointing it out. I've modified my original comment.

**Comment by Michail-82** [comment] 2024-06-01 00:06
can someone explain the steps to install? 

I've saved the whl file in a folder called Pymel
Then ran the mayapy `-m pip install pymel-1.4.1b1-py2.py3-none-any.whl --user` command in the command prompt but nothing happened.  

Eventually I ran `pip install pymel-1.4.1b1-py2.py3-none-any.whl` that did something.
Then created another command prompt with `C:\Program Files\Autodesk\Maya2025\bin` amd `mayapy -m pip install pymel`

now Maya wiont start :D

**Comment by Michail-82** [comment] 2024-06-01 00:21
![image](https://github.com/LumaPictures/pymel/assets/55023080/5081eabf-2dad-456b-9674-da24e701e4e7)
pymel seems to be in there but prob missing mayapy???

**Comment by Michail-82** [comment] 2024-06-01 00:39
ok as a newb I think figured it out, 
for anyone strrugling get the whl file from github. 
save it somwhere (mine was c:\Pymel)

I did a few things so not sure which caused it finally work.

1. Open command pormpt
2. Type in cd c:\Pymel
3. type pip install pymel-1.4.1b1-py2.py3-none-any.whl
4. repeat step 2
5. type in "C:\Program Files\Autodesk\Maya2025\bin\mayapy.exe" -m pip install pymel-1.4.1b1-py2.py3-none-any.whl
6. open maya Pymel now works

**Comment by chadrik** [comment] 2024-06-01 19:38
Hi all, sorry for the silence here.   Everyone who maintained this project at Luma has moved on to other companies, including me.  I have been super busy lately with my new job, so it's been hard to find the time for this, I apologize.  That said, I'd really like to see this project and its community survive and thrive.  

The problem as it stands is that I don't have the ability to merge anything in this project (or any projects owned by the LumaPictures org).   I've emailed several times over the past few months.  I just emailed everyone again.  

I do still have the keys to PyPI, so I can help get an official release out to PyPI.

@iamsleepy  Can you help me get this out?  

If you can do step 7 (changelog) and the first parts of step 9 (update the version in pymel/__init__.py, supported Maya versions in README.md, minimum supported python versions in pyproject.toml), then I can do the rest. 

Once I get the keys back to the project I can also add you as a contributor and we can get through these releases together, if that's interesting to you.

**Comment by iamsleepy** [comment] 2024-06-01 23:39
Hi @chadrik Let me try to work on the change log tomorrow.

**Comment by chadrik** [comment] 2024-06-01 23:59
I had a quick look and it’s going to be very simple because there haven’t
been many changes.

**Comment by faziok** [comment] 2024-06-18 15:12
@chadrik any update on this?

**Comment by Nonplus1** [comment] 2024-06-24 21:00
Patiently awaiting updates also! Would really appreciate the effort @iamsleepy @chadrik :)

**Comment by mortenbohne** [comment] 2024-07-08 14:57
hey, thanks for the great work. 
@iamsleepy I did run into a minor issue in pymel-1.4.1b1 that seems connected to the PySide->PySide6 update:
`pm.uitypes.toPySideControl(pm.MelGlobals.get("gMainWindow"))` no longer works (i'm guessing it's a matter of changing to shiboken6)

**Comment by iamsleepy** [comment] 2024-07-11 03:42
Hi @mortenbohne , I updated the codes related to PySide and PyQt4. It should be working now.

**Comment by Spoonfishlee** [comment] 2024-07-16 20:44
Damn man, you are a **HERO**! Just tried to install Pymel on 2025 for three hours. @iamsleepy

**Comment by AndyMac521** [comment] 2024-08-01 20:47
Hey, complete python dummy here, but hoping someone could help with this error. Other python scripts work fine, but this fSpy importer returns:

Error: ModuleNotFoundError: file C:\Users/andym/Documents/maya/2025/scripts\maya_fspy\ui.py line 23: No module named 'PySide2'

ideas? Thanks

**Comment by DouglasWilcox** [comment] 2024-08-01 21:12
@AndyMac521 for Maya 2025, these should be **PySide6** and **shiboken6**.  If your tools are used on multiple maya versions you'll have to handle it by checking version at startup.

**Comment by YKdvd** [comment] 2024-09-23 18:23
Is it known if/when the "iamsleepy" 1.5.0 version or an equivalent will be published to PyPi?  I'm tweaking our Python infrastructure stuff for testing Maya2025, and I've got that unofficial wheel available to our building system use for Python3.11/Maya2025, but it would be nice to have it blessed and come from PyPi when possible.

**Comment by SabrinaTaoujni** [comment] 2024-09-25 12:15
Heeeeeeeeeeeeelp I've downloaded the zip file @iamsleepy uploaded but I have no idea what to do with it, I just need Pymel to get a Maya script working T-T
I read through the whole thread, it seems like people got it working but I don't know how to, I don't know what a sys.path is and I've tried the download command for windows cmd prompt but it's not working either... 
Can any kind soul explain step by step how to install this thing please

**Comment by CraigLaMorte** [comment] 2024-09-25 15:24
> Heeeeeeeeeeeeelp I've downloaded the zip file @iamsleepy uploaded but I have no idea what to do with it, I just need Pymel to get a Maya script working T-T I read through the whole thread, it seems like people got it working but I don't know how to, I don't know what a sys.path is and I've tried the download command for windows cmd prompt but it's not working either... Can any kind soul explain step by step how to install this thing please

Drop the pymel folder in here and you shold be able to access pymel within maya 2025 - C:\Program Files\Autodesk\Maya2025\Python\Lib\site-packages

**Comment by JasonGilholme** [comment] 2024-09-25 20:04
Hi,

Just wanted to let you know that I'm working towards getting iamsleepy's PR released.  I'm picking this up having not been involved in it's prior development so bare with me while we get this across the line. Once I've got access to pypi and Chad has confirmed that the PR is g2g then I'll work through the release process.

Apologies for all the inconvenience - it's been a pretty wild 6-12 months in this industry that's for sure!  Hope you're all well.

Jase

**Comment by mostlyhuman** [comment] 2024-10-11 09:27
> Hi,
> 
> Just wanted to let you know that I'm working towards getting iamsleepy's PR released. I'm picking this up having not been involved in it's prior development so bare with me while we get this across the line. Once I've got access to pypi and Chad has confirmed that the PR is g2g then I'll work through the release process.
> 
> Apologies for all the inconvenience - it's been a pretty wild 6-12 months in this industry that's for sure! Hope you're all well.
> 
> Jase

Any update on this? Cheers!

**Comment by mostlyhuman** [comment] 2024-10-17 22:36
Anyone? Anyone? Bueller? Bueller?

**Comment by JasonGilholme** [comment] 2024-10-21 11:18
Heya, 

Apologies for the delay, we don't have a large team so these sorts of things happen in my personal time being squeezed in where it can.  Good news is though I'm pretty close to being confident in pushing this out.  I'm anticipating doing it before the end of this week.

Like I mentioned before, I'm picking this up from a blank slate so I wanted to take the time to get better acquainted with the process and setup.  I also took the opportunity to iron out some release procedures on our side so it's more automated and repeatable internally for us so we can get this stuff done quicker in the future.

Thanks again!
Jase

**Comment by JasonGilholme** [comment] 2024-10-28 05:16
Hi again,

I'm happy to say that after some internal testing and a few extra tweaks I've merged @iamsleepy's PR and pushed a build of pymel 1.5.0 to pypi.

We're not running maya 2025 internally so the new caches haven't had a production run just yet, however the little tweaks I added were to get the tests passing in 2025.3.

Thanks once again for your patience on this one, I very much appreciate it! Also a big thanks to @iamsleepy for doing the vast majority of the work here.  Thanks man.

Jase

**Closed by JasonGilholme** 2024-10-28 05:16 UTC

**Comment by rasputin468** [comment] 2024-11-04 14:25
Hi

> ok as a newb I think figured it out, for anyone strrugling get the whl file from github. save it somwhere (mine was c:\Pymel)
> 
> I did a few things so not sure which caused it finally work.
> 
>     1. Open command pormpt
> 
>     2. Type in cd c:\Pymel
> 
>     3. type pip install pymel-1.4.1b1-py2.py3-none-any.whl
> 
>     4. repeat step 2
> 
>     5. type in "C:\Program Files\Autodesk\Maya2025\bin\mayapy.exe" -m pip install pymel-1.4.1b1-py2.py3-none-any.whl
> 
>     6. open maya Pymel now works
> 
> 
> Big thanks to @iamsleepy for the file!!!!

Hello. I tried to follow the steps and I meant to do everything correctly, but mgear menu didn't appear in maya. Have I add 'C:\mgear4-4.2.10\release\platforms' a new 2025 folder? Thanks in advance for help
