### ISSUE TITLE
Templates don't work in Python 3

### ISSUE THREAD

**Issue by formjune** [LumaPictures/pymel#461] opened 2022-11-19 08:18 UTC
Maya is unable to draw templates defined via pymel.core.ui.AETemplate.
It can be fixed by opening pymel.core.uitypes.py and removing argument -1 from __import__() method

**Comment by chadrik** [comment] 2022-12-30 22:37
This is a duplicate of #447 which is now fixed

**Closed by chadrik** 2022-12-30 22:37 UTC
